const actions = {
  USER_REQUEST: 'USER_REQUEST',
  USER_ERROR: 'USER_ERROR',
  USERS_SUCCESS: 'USERS_SUCCESS',
  USER_SUCCESS: 'USER_SUCCESS',
  GET_POST_REQUEST: 'GET_POST_REQUEST',
  GET_POST_ERROR: 'GET_POST_ERROR',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POST_SUCCESS: 'GET_POST_SUCCESS',
  GET_COMMENTS_REQUEST: 'GET_COMMENTS_REQUEST',
  GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
  GET_COMMENTS_ERROR: 'GET_COMMENTS_ERROR',
};

export default actions;
